# -*- coding: utf-8 -*-
"""EE2703  APL Assignment 6 EE23B188

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fDkyK57ibw4fcRr3BiM-46D8CmFckfvA
"""

def points(a, b, n):
    # Create a list of points from a to b with n intervals
    p = []
    d = (b - a) / n  # Interval size
    for i in range(n + 1):
        p.append(a + i * d)
    return p

def f_lis(f, p):
    # Apply function f to each point in p and return the results as a list
    lis = []
    for i in p:
        lis.append(f(i))
    return lis

import numpy as np

def py_trapz(f, a, b, n):
  d = (b-a)/ n
  A = 0
  for i in range(n):
    x1 = a + i*d                   # compute points and their heighsts
    x2 = a + (i+1)*d
    h1 = f(x1)
    h2 = f(x2)
    A += (h1 + h2)*d/2     # Add up areas of trapexium

  return A

# Commented out IPython magic to ensure Python compatibility.
# %load_ext Cython

# Commented out IPython magic to ensure Python compatibility.
# %%cython --annotate
# import cython
# # Turn off bounds checking
# @cython.boundscheck(False)
# # Turn off wraparound
# @cython.wraparound(False)
# 
# 
# def cy_trapz( f, double a, double b, int n):
#   cdef double d , A, x1, x2, h1, h2
#   cdef int i
#   d = (b-a)/ n
#   A = 0
#   for i in range(n):
#     x1 = a + i*d
#     x2 = a + (i+1)*d
#     h1 = f(x1)
#     h2 = f(x2)
#     A += (h1 + h2)*d/2
# 
#   return A
#

"""# 1. f(x) = x^2, Actual value = 1/3"""

def f(x):
  return x**2

"""## n = 1000"""

a = 0
b = 1
n = 1000

# Commented out IPython magic to ensure Python compatibility.
print("np method value is", np.trapz(f_lis(f, points(a,b,n)),x = points(a, b, n)))
print("time taken by np method")
# %timeit np.trapz(f_lis(f, points(a,b,n)), points(a, b, n))

# Commented out IPython magic to ensure Python compatibility.
print("PY method value is", py_trapz(f,a,b,n))
print("time taken by py method")
# %timeit py_trapz(f,a,b,n)

# Commented out IPython magic to ensure Python compatibility.
print("CY method value is", cy_trapz(f,a,b,n))
print("time taken by cy method")
# %timeit cy_trapz(f,a,b,n)

"""## n = 100000"""

a = 0
b = 1
n = 100000

# Commented out IPython magic to ensure Python compatibility.
print("np method value is", np.trapz(f_lis(f, points(a,b,n)),x = points(a, b, n)))
print("time taken by np method")
# %timeit np.trapz(f_lis(f, points(a,b,n)), points(a, b, n))

# Commented out IPython magic to ensure Python compatibility.
print("PY method value is", py_trapz(f,a,b,n))
print("time taken by py method")
# %timeit py_trapz(f,a,b,n)

# Commented out IPython magic to ensure Python compatibility.
print("CY method value is", cy_trapz(f,a,b,n))
print("time taken by cy method")
# %timeit cy_trapz(f,a,b,n)

"""# 2. sinx, actual value = 2"""

import math

def f(x):
  return math.sin(x)

"""## n = 1000"""

a = 0
b = math.pi
n = 1000

# Commented out IPython magic to ensure Python compatibility.
print("np method value is", np.trapz(f_lis(f, points(a,b,n)),x = points(a, b, n)))
print("time taken by np method")
# %timeit np.trapz(f_lis(f, points(a,b,n)), points(a, b, n))

# Commented out IPython magic to ensure Python compatibility.
print("PY method value is", py_trapz(f,a,b,n))
print("time taken by py method")
# %timeit py_trapz(f,a,b,n)

# Commented out IPython magic to ensure Python compatibility.
print("CY method value is", cy_trapz(f,a,b,n))
print("time taken by cy method")
# %timeit cy_trapz(f,a,b,n)

"""## n = 100000"""

a = 0
b = math.pi
n = 100000

# Commented out IPython magic to ensure Python compatibility.
print("np method value is", np.trapz(f_lis(f, points(a,b,n)),x = points(a, b, n)))
print("time taken by np method")
# %timeit np.trapz(f_lis(f, points(a,b,n)), points(a, b, n))

# Commented out IPython magic to ensure Python compatibility.
print("PY method value is", py_trapz(f,a,b,n))
print("time taken by py method")
# %timeit py_trapz(f,a,b,n)

# Commented out IPython magic to ensure Python compatibility.
print("CY method value is", cy_trapz(f,a,b,n))
print("time taken by cy method")
# %timeit cy_trapz(f,a,b,n)

"""# 3. e^x , e-1"""

import math

def f(x):
  return (math.e)**x

"""## n = 1000"""

a = 0
b = 1
n = 1000

# Commented out IPython magic to ensure Python compatibility.
print("np method value is", np.trapz(f_lis(f, points(a,b,n)),x = points(a, b, n)))
print("time taken by np method")
# %timeit np.trapz(f_lis(f, points(a,b,n)), points(a, b, n))

# Commented out IPython magic to ensure Python compatibility.
print("PY method value is", py_trapz(f,a,b,n))
print("time taken by py method")
# %timeit py_trapz(f,a,b,n)

# Commented out IPython magic to ensure Python compatibility.
print("CY method value is", cy_trapz(f,a,b,n))
print("time taken by cy method")
# %timeit cy_trapz(f,a,b,n)

"""## n = 100000"""

a = 0
b = 1
n = 100000

# Commented out IPython magic to ensure Python compatibility.
print("np method value is", np.trapz(f_lis(f, points(a,b,n)),x = points(a, b, n)))
print("time taken by np method")
# %timeit np.trapz(f_lis(f, points(a,b,n)), points(a, b, n))

# Commented out IPython magic to ensure Python compatibility.
print("PY method value is", py_trapz(f,a,b,n))
print("time taken by py method")
# %timeit py_trapz(f,a,b,n)

# Commented out IPython magic to ensure Python compatibility.
print("CY method value is", cy_trapz(f,a,b,n))
print("time taken by cy method")
# %timeit cy_trapz(f,a,b,n)

"""# 4.1/x, ln(2)"""

def f(x):
  return 1/x

"""## n = 1000"""

a = 1
b = 2
n = 1000

# Commented out IPython magic to ensure Python compatibility.
print("np method value is", np.trapz(f_lis(f, points(a,b,n)),x = points(a, b, n)))
print("time taken by np method")
# %timeit np.trapz(f_lis(f, points(a,b,n)), points(a, b, n))

# Commented out IPython magic to ensure Python compatibility.
print("PY method value is", py_trapz(f,a,b,n))
print("time taken by py method")
# %timeit py_trapz(f,a,b,n)

# Commented out IPython magic to ensure Python compatibility.
print("CY method value is", cy_trapz(f,a,b,n))
print("time taken by cy method")
# %timeit cy_trapz(f,a,b,n)

"""## n = 100000"""

a = 1
b = 2
n = 100000

# Commented out IPython magic to ensure Python compatibility.
print("np method value is", np.trapz(f_lis(f, points(a,b,n)),x = points(a, b, n)))
print("time taken by np method")
# %timeit np.trapz(f_lis(f, points(a,b,n)), points(a, b, n))

# Commented out IPython magic to ensure Python compatibility.
print("PY method value is", py_trapz(f,a,b,n))
print("time taken by py method")
# %timeit py_trapz(f,a,b,n)

# Commented out IPython magic to ensure Python compatibility.
print("CY method value is", cy_trapz(f,a,b,n))
print("time taken by cy method")
# %timeit cy_trapz(f,a,b,n)

"""# 1. again:
10 milllion trapeziums, actual value = 333.33333
"""

def f(x):
  return x**2

a = 0
b = 10
n = 10**7

# Commented out IPython magic to ensure Python compatibility.
print("np method value is", np.trapz(f_lis(f, points(a,b,n)),x = points(a, b, n)))
print("time taken by np method")
# %timeit np.trapz(f_lis(f, points(a,b,n)), points(a, b, n))

# Commented out IPython magic to ensure Python compatibility.
print("PY method value is", py_trapz(f,a,b,n))
print("time taken by py method")
# %timeit py_trapz(f,a,b,n)

# Commented out IPython magic to ensure Python compatibility.
print("CY method value is", cy_trapz(f,a,b,n))
print("time taken by cy method")
# %timeit cy_trapz(f,a,b,n)